---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: jenkins-server
    run_list:
        - recipe[met-jenkins::default]
        - recipe[met-bora-ci::jenkins]
    attributes:
