name                'met-bora-ci'
maintainer          'MET Norway'
maintainer_email    'kimtj@met.no'
license             'All rights reserved'
description         'Installs/Configures met-bora-ci'
long_description    'Installs/Configures met-bora-ci'
version             '2.0.1'

depends             'apt',          '~> 2.6'
depends             'met-jenkins',  '~> 0.2'
depends             'phabricator',  '~> 1.4'
depends             'docker',       '~> 0.35'
