name                'met-bora-ci'
maintainer          'MET Norway'
maintainer_email    'kimtj@met.no'
license             'All rights reserved'
description         'Installs/Configures met-bora-ci'
long_description    'Installs/Configures met-bora-ci'
version             '0.7.0'

depends             'apt',          '~> 2.6'
depends             'go',           '~> 0.2'
depends             'jenkins',      '~> 2.1'
depends             'nginx',        '~> 2.7'
depends             'firewall',     '~> 0.11'
depends             'phabricator',  '~> 1.4'
