name                'met-api-cd'
maintainer          'MET Norway'
maintainer_email    'kimtj@met.no'
license             'All rights reserved'
description         'Installs/Configures met-api-cd'
long_description    'Installs/Configures met-api-cd'
version             '3.0.0'

depends             'apt',          '~> 2.6'
depends             'met-jenkins',  '~> 0.2'
depends             'phabricator',  '~> 1.4'
depends             'docker',       '~> 0.35'
